"""
model_openvla_pipeline_analysis.py

B1 VLA Foundation Model Scientist
Analysis of OpenVLA vanilla (7B) and OpenVLA-OFT pipeline.
Focus: data format, GPU requirements, conversion from LeRobot v3, custom robot reports.

Run with: python model_openvla_pipeline_analysis.py
Outputs: claudedocs/OPENVLA_PIPELINE_ANALYSIS.md
"""

ANALYSIS = """
# OpenVLA Pipeline Analysis
# Generated by: model_openvla_pipeline_analysis.py
# Date: 2026-03-27
# Source: GitHub repos (openvla/openvla, moojink/openvla-oft) + issue tracker

##############################################################################
# 1. OpenVLA VANILLA (7B) — Architecture
##############################################################################

Architecture:
  - Prismatic VLM: DINOv2 + SigLIP (fused dual vision backbone, 224px) + Llama-2 7B
  - Total params: ~7.5B
  - Vision: DINOv2-L/14 (307M) + SigLIP-L (428M), feature fusion via linear projection
  - Language backbone: Llama-2 7B (autoregressive)
  - NO separate action head — actions are LLM token outputs
  - Pretraining data: Open X-Embodiment (OXE), 970K trajectories, diverse embodiments

Action representation (VANILLA — critical):
  - Discrete tokens: 256 bins per action dimension, uniform binning in [-1, 1]
  - N action dims → N sequential tokens (autoregressive generation)
  - Token assignment: last 256 vocab tokens of Llama-2 (least-used tokens overwritten)
  - Joint angles must be normalized to [-1, 1] range before discretization
  - Decoded: bin center lookup → de-normalize → continuous joint angle
  - Resolution: 2/256 = ~0.0078 per step → at 180° range → ~1.4° resolution

Action space details:
  - Input: normalized action in [-1, 1] per dim
  - Process: np.clip → np.digitize(bins=256) → map to vocab[-256:]
  - Output: token IDs → bin center → de-normalize (via dataset_statistics.json)
  - NO action chunking in vanilla
  - Single-step prediction: one action vector per inference call
  - Frequency: 5-10 Hz recommended (autoregressive is slow)

Inference speed:
  - Autoregressive generation of N tokens (N = action dims)
  - 7-DOF arm: 7 sequential decode steps → slow
  - Practical: ~1-3 Hz on A100 without optimization
  - FLASH ATTENTION 2 required for reasonable speed

##############################################################################
# 2. OpenVLA VANILLA — Training / Fine-tuning
##############################################################################

Fine-tuning script: vla-scripts/finetune.py
Method: LoRA (primary), Full fine-tune (advanced, requires FSDP + 8x A100)

LoRA fine-tuning config (default):
  - lora_rank = 32
  - lora_alpha = min(rank, 16) = 16
  - lora_dropout = 0.0
  - target_modules = "all-linear"  # all attention + FFN layers
  - init_lora_weights = "gaussian"
  - base_lr = 5e-4
  - batch_size = 16 (A100 80GB), 4-8 (A100 40GB)
  - optimizer: AdamW (constant LR, no warmup/decay in vanilla script!)
  - max_steps: 200K default
  - image_aug: random 90% center crop + color jitter

CRITICAL WARNINGS from vanilla training:
  1. No LR scheduler — flat 5e-4 throughout. OFT adds MultiStepLR (10x decay at N steps)
  2. batch_size × lr must scale: smaller GPU → reduce batch, reduce LR proportionally
  3. Dataset statistics: dataset_statistics.json MUST be saved at training time
     → used for de-normalizing actions at inference time
     → if missing, unnorm_key lookup fails → garbage actions
  4. 5-10 Hz control frequency recommended (not 30 Hz like SmolVLA's 50-step chunks)

Data format: RLDS (TensorFlow Datasets)
  - Required: tensorflow-datasets, tfds pipeline
  - Schema: episodes → steps → {observation: {image, state}, action, language_instruction}
  - Image: any size, resized to model input (224x224 for vanilla)
  - Action: float32 array, normalized to [-1, 1]
  - Language: raw text string + USE embedding (Universal Sentence Encoder, 512-dim)
  - NO video format — individual frames stored as PNG images

RLDS conversion from LeRobot v3 (parquet + mp4):
  REQUIRED STEPS:
  Step 1: Extract frames from mp4 → numpy arrays
  Step 2: Load action/state from parquet → numpy arrays
  Step 3: Normalize actions to [-1, 1] (save stats for de-normalization!)
  Step 4: Add USE language embeddings (512-dim, requires TF Hub connection)
  Step 5: Write RLDS dataset via kpertsch/rlds_dataset_builder
  Step 6: Register dataset in:
    - prismatic/vla/datasets/rlds/oxe/configs.py (schema definition)
    - prismatic/vla/datasets/rlds/oxe/transforms.py (normalization transform)
    - prismatic/vla/datasets/rlds/oxe/mixtures.py (mixture registration)
  Step 7: tfds build --overwrite
  ESTIMATE: 2-4 days of engineering work for clean conversion

Key configs.py entry for 6-DOF joint space:
  "roarm_m3_pick": {
    "image_obs_keys": {"primary": "top", "secondary": None, "wrist": None},
    "depth_obs_keys": {"primary": None, "secondary": None, "wrist": None},
    "state_obs_keys": ["observation.state"],
    "state_encoding": StateEncoding.JOINT,
    "action_encoding": ActionEncoding.JOINT_POS,   # absolute joint positions
  }

##############################################################################
# 3. OpenVLA VANILLA — GPU Requirements
##############################################################################

Full fine-tune (7.5B params, FSDP):
  - Minimum: 8x A100 80GB
  - NOT feasible on single GPU or consumer hardware
  - Requires PyTorch FSDP (sharded optimizer states across nodes)

LoRA fine-tune (r=32, all-linear):
  - 1x A100 80GB: batch_size=16-24 → comfortable
  - 1x A100 40GB: batch_size=4-8 → feasible (~35-40GB peak)
  - 1x RTX 4090 24GB: batch_size=1-2 → marginal (27GB minimum per docs)
  - RTX 4090 Laptop (16.7GB): NOT FEASIBLE without QLoRA
  - Note: bfloat16 model weights alone ≈ 15GB

QLoRA fine-tune (4-bit NF4 quantization + LoRA):
  - Available: --use_quantization True in finetune.py
  - RTX 4090 24GB: batch_size=4-8 → feasible (~18-22GB peak)
  - RTX 4090 Laptop (16.7GB): batch_size=1-2 → tight but possible
  - Trade-off: reduces memory significantly but HURTS PERFORMANCE (official warning)
  - Recommendation: use only as last resort

Inference only:
  - bfloat16: ~15GB → RTX 4090 24GB: YES; RTX 4090 Laptop 16.7GB: MARGINAL
  - 4-bit quantized: ~8-10GB → RTX 4090 Laptop: YES
  - 8-bit quantized: ~11-13GB → RTX 4090 Laptop: YES

Cloud recommendations for LoRA fine-tune:
  - A100 40GB (VAST.ai): ~$1.5-2/hr × 100K steps × ~2hr = ~$4-8
  - A100 80GB (VAST.ai): ~$2.5-3/hr → comfortable batch_size=16
  - H100 (GCP spot): fastest but expensive

##############################################################################
# 4. OpenVLA-OFT — What Changed
##############################################################################

Paper: arXiv 2502.19645 (Kim, Finn, Liang 2025) — RSS 2025
Repo: https://github.com/moojink/openvla-oft

KEY CHANGE 1: Continuous actions via L1 regression head
  - Replaces 256-bin discrete token prediction
  - New component: L1RegressionActionHead (MLPResNet, 2 blocks)
    Input: LLM hidden states of action token positions
    Output: continuous float32 action chunk
  - Loss: L1 (continuous) not cross-entropy (discrete tokens)
  - No quantization error → better precision

KEY CHANGE 2: Action chunking via parallel decoding
  - chunk_size: 8 (LIBERO), 25 (ALOHA), 5 (BridgeV2)
  - All chunk actions predicted in PARALLEL (not autoregressive)
  - Method: inject N "action tokens" into input sequence, predict all simultaneously
  - Speed: 25-50x faster than vanilla autoregressive (109.7 Hz reported for 8-step chunks)

KEY CHANGE 3: Multi-image input
  - Supports 1, 2, or 3 images (--num_images_in_input)
  - ALOHA: 3 images (1 third-person + 2 wrist cameras)
  - LIBERO: 2 images (1 third-person + 1 wrist camera)

KEY CHANGE 4: FiLM conditioning (optional, "OFT+" variant)
  - Feature-wise Linear Modulation applied to vision backbone
  - Infuses language embedding into visual features
  - Improves language grounding significantly:
    - Without FiLM: 33% success on language-variation tasks (≈ random)
    - With FiLM: >60% on same tasks
  - Set --use_film True for language-sensitive tasks

KEY CHANGE 5: LR scheduler
  - MultiStepLR with 10x decay at num_steps_before_decay
  - Default: decay at 100K steps, train to 150K total
  - Better convergence than flat LR in vanilla

KEY CHANGE 6: Proprioceptive state input (optional)
  - ProprioProjector maps state vector → LLM embedding space
  - Prepended to input sequence
  - Tested with 7-8 DOF joint angles as state

Action normalization:
  - LIBERO: BOUNDS_Q99 (clip outliers at 1st/99th percentile → normalize to [-1,1])
  - ALOHA: BOUNDS (min/max normalization, absolute joint angles, NO clipping)
  - CRITICAL: ALOHA uses BOUNDS not BOUNDS_Q99 because clipping absolute joint angles
    would prevent the robot from reaching extreme but valid positions

Chunk size guidelines (from paper + issues):
  - 1 sec of actions is a good default
  - ALOHA 25Hz → 25-step chunk
  - LIBERO 30Hz → 8-step chunk (1 sec ÷ 8 = 125ms per step at ~8Hz control)
  - BridgeV2 5Hz → 5-step chunk
  - RoArm-M3 at 30fps → 30-step chunk for 1-sec, or 8-step for 250ms

OFT data format: STILL RLDS
  - Core data pipeline unchanged from vanilla
  - Must still convert to RLDS, register configs/transforms/mixtures
  - No LeRobot v3 support out-of-the-box
  - Issue #152 confirmed: RLDS is the only officially supported path

Custom PyTorch Dataset support:
  - Documented in vanilla finetune.py comments but not demonstrated
  - OFT finetune.py has same DummyDataset comment path
  - Not tested by maintainers; unofficial workaround only
  - Requires: correct batch format + action normalization + proprio handling

##############################################################################
# 5. OpenVLA-OFT — GPU Requirements
##############################################################################

LoRA fine-tune (r=32, OFT recipe, bfloat16):
  - From README: "between 1-8 GPUs with 27-80 GB depending on setup"
  - batch_size=8: ~62 GB VRAM (A100 80GB or H100)
  - batch_size=1: ~25 GB VRAM (A100 40GB feasible)
  - For single-GPU with OFT recipe:
    - A100 80GB: batch_size=4-8 → recommended
    - A100 40GB: batch_size=1-2 → feasible but slow convergence
    - RTX 4090 24GB: batch_size=1 → ~25-27GB needed → NOT FEASIBLE without QLoRA
    - RTX 4090 Laptop 16.7GB: NOT FEASIBLE (even batch=1 too large)

Inference only:
  - From README: ~16 GB VRAM for LIBERO (1-2 images)
  - ~18 GB VRAM for ALOHA (3 images)
  - RTX 4090 Laptop 16.7GB: MARGINAL for 1-image inference
  - Practical cloud deployment: A100 40GB → comfortable

QLoRA for OFT:
  - Issue #134 asks about QLoRA for OFT → no official answer (open issue)
  - Not tested/supported in official OFT codebase as of 2026-03-27
  - Would require adding BitsAndBytesConfig (same as vanilla)

##############################################################################
# 6. LeRobot v3 → RLDS Conversion for OpenVLA
##############################################################################

Our dataset (lerobot_dataset_v5):
  - 136 episodes, 13470 frames at 30fps
  - 6-DOF joint angles (base, shoulder, elbow, wrist_pitch, wrist_roll, gripper)
  - Single camera: observation.images.top (1280x720 RGB, AV1 video)
  - Task: "Pick up the white box" (1 task)
  - Format: LeRobot v3 (parquet + mp4 per episode)

Conversion pipeline (RLDS path):

Option A: Full RLDS conversion (2-4 days, required for official pipeline)
  1. Decode mp4 → per-frame PNG (ffmpeg or cv2)
  2. Read parquet → action/state arrays per episode
  3. Compute normalization stats (min/max, mean/std per joint)
  4. Add USE language embeddings (512-dim via TF Hub)
  5. Write via rlds_dataset_builder custom class
  6. tfds build --overwrite → generates TFRecord shards
  7. Register in configs.py, transforms.py, mixtures.py
  8. Test: check dataset_statistics.json matches normalization

Option B: Custom PyTorch Dataset (unofficial, 1 day)
  - Write torch Dataset reading parquet directly
  - Manual action normalization to [-1, 1]
  - Provide DummyDataset-compatible batch format
  - RISK: not tested by maintainers; may miss edge cases

Recommended path: Option A (RLDS)
  - Official + tested
  - dataset_statistics.json generated automatically
  - Works with both vanilla and OFT

Key normalization decision for 6-DOF joint angles:
  - Use BOUNDS (not BOUNDS_Q99) since joint angles are absolute and we need
    full range coverage (same rationale as ALOHA)
  - Q99 would clip valid extreme positions → robot can't reach them at inference

Image resizing:
  - OpenVLA vanilla: 224x224 (DINOv2/SigLIP-224px)
  - Our input: 1280x720 → center crop → resize to 224x224
  - Apply same transform at inference time (--center_crop True)

##############################################################################
# 7. Custom Robot Reports from GitHub Issues
##############################################################################

Non-standard embodiments tried:
  1. WidowX 250s (Trossen, 6-DOF): Issue #312
     - Zero-shot ~10% before fine-tuning
     - After fine-tuning (5K steps): model barely moves, tiny constant actions
     - Root cause: unnorm_key mismatch + likely too few steps
     - Resolution: not provided in thread

  2. UR3 (Universal Robots, 6-DOF): Issue #292
     - Single camera input → pick primary camera only
     - LoRA fine-tuning: standard path applies
     - Multi-view: use primary camera only (vanilla supports 1 image)

  3. 7-DOF custom arm (Issue #149, OFT):
     - Successfully adapted constants.py for 8-DOF (7 joints + gripper)
     - Used ActionEncoding.JOINT_POS (absolute angles)
     - Had to add JOINT_POS to materialize.py validation list
     - Added custom transforms.py entry

  4. PyBullet sim (210 demos, 5Hz): Issue #304
     - Model converged on training but near-zero success on eval
     - Conclusion: fine-tuning distribution matters, not just step count
     - Likely cause: sim-to-real gap + 10K steps insufficient

Key failure modes reported:
  - Constant/tiny actions after fine-tuning: usually unnorm_key mismatch
  - Robot barely moves: LR too high for small batch, or dataset too small
  - 0% success after LoRA: LR × batch_size scaling issue (fix: reduce LR if reducing batch)
  - Sim fine-tuning → real failure: sim image OOD for DINOv2/SigLIP

##############################################################################
# 8. SmolVLA vs OpenVLA vs OpenVLA-OFT Comparison (Research Table)
##############################################################################

| Property            | SmolVLA (450M)     | OpenVLA-7B (7B)     | OpenVLA-OFT (7B)    |
|--------------------|--------------------|---------------------|---------------------|
| VLM backbone       | SmolVLM (SigLIP+SmolLM2) | Prismatic (DINOv2+SigLIP+Llama2) | Same as vanilla |
| Action rep         | Continuous (flow matching) | Discrete (256 bins) | Continuous (L1 regression) |
| Action chunking    | 50 steps (default) | None (single step)  | 5-25 steps (configurable) |
| Inference speed    | ~108ms/step (10 denoise) | ~200-500ms (autoregressive 7 tokens) | ~10-20ms (parallel decode) |
| Pretraining        | SO-100 only (11K ep) | OXE (970K trajectories, diverse) | Same as vanilla |
| Fine-tune VRAM     | 9.85GB (batch=64, RTX 4090) | 27GB (batch=1 LoRA, A100 40GB) | 25-62GB (batch=1-8 LoRA) |
| Fine-tune method   | Full FT (no LoRA needed) | LoRA r=32         | LoRA r=32           |
| Data format        | LeRobot v3 (parquet+mp4) | RLDS (TFRecord)  | RLDS (TFRecord)     |
| LeRobot support    | NATIVE             | NO (2-4 day conversion) | NO (2-4 day conversion) |
| Control freq       | 30fps (50-step chunks) | 5-10 Hz           | 8-50 Hz (chunk-dependent) |
| Novel embodiment   | OOD vs SO-100      | OOD vs OXE (better pretrain diversity) | Same as vanilla |
| Custom robot       | RoArm-M3 tested (100%) | WidowX, UR3 (partial) | 7-DOF (partial, issue #149) |
| Language grounding | Frozen VLM (strong) | Full VLM (strong) | + FiLM (strongest) |
| Ablation cleanliness | Full FT no LoRA (clean) | LoRA only (confounder) | LoRA only (confounder) |

For research comparison (CoRL 2026):
  - SmolVLA: efficient baseline, consumer GPU, native LeRobot format
  - OpenVLA-OFT: SOTA fine-tuning method, LoRA, RLDS required, cloud GPU
  - OpenVLA vanilla: NOT recommended (slow inference, discrete actions inferior to OFT)

##############################################################################
# 9. Critical Implementation Notes for RoArm-M3
##############################################################################

For OpenVLA-OFT adaptation to RoArm-M3 6-DOF:

1. constants.py — add new platform:
   ROARM_CONSTANTS = {
     "NUM_ACTIONS_CHUNK": 8,          # 8-step chunks at 30fps = 267ms
     "ACTION_DIM": 6,                 # 6-DOF
     "PROPRIO_DIM": 6,                # same as action dim
     "ACTION_PROPRIO_NORMALIZATION_TYPE": NormalizationType.BOUNDS  # not BOUNDS_Q99
   }

2. Data: RLDS conversion required
   - 2-4 days engineering (frame extraction, normalization, TF writer, registration)
   - Alternative: custom PyTorch Dataset (unofficial, 1-2 days but risky)

3. Action normalization:
   - Use joint angle ranges as bounds (e.g., base: -190 to 190)
   - NOT Q99 clipping (would prevent extreme positions)
   - Save normalization stats carefully (dataset_statistics.json)

4. Control frequency:
   - Our 30fps data → if using 8-step chunks = 267ms lag
   - OK for pick tasks, too slow for dynamic tasks
   - Consider 15-step chunks (500ms) for smoother behavior

5. GPU: A100 40GB (cloud) for fine-tuning
   - batch_size=2-4 with single A100 40GB
   - Expected: 100K-150K steps for LIBERO-quality result
   - Cost estimate: ~$20-30 on VAST.ai spot

6. Inference on RTX 4090 Laptop (16.7GB):
   - base model bfloat16 = ~15GB → marginal
   - With 4-bit quantization → ~9GB → feasible
   - Issue: train/test GPU mismatch may hurt performance
     → merge LoRA on A100, test on A100 if possible
"""

if __name__ == "__main__":
    import os
    out_path = "/home/cgxr/Documents/Robotics/RoArm_Project/claudedocs/OPENVLA_PIPELINE_ANALYSIS.md"
    # Write the markdown version (strip python docstring formatting)
    md_content = ANALYSIS.replace('"""', '').strip()
    with open(out_path, 'w') as f:
        f.write(md_content)
    print(f"Written to: {out_path}")
    print("\n--- Summary ---")
    print("OpenVLA vanilla: RLDS required, LoRA, 256-bin discrete, no chunking, A100 40GB minimum")
    print("OpenVLA-OFT:     RLDS required, LoRA, continuous L1, action chunking, 25-62GB VRAM")
    print("LeRobot v3 → RLDS: 2-4 days engineering, no official shortcut as of 2026-03-27")
    print("Consumer GPU (16.7GB): NOT feasible for OFT training; inference marginal (bfloat16)")
